/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorDashboardRouteImport } from './routes/doctor.dashboard'
import { Route as DoctorPatientsIndexRouteImport } from './routes/doctor.patients.index'
import { Route as DoctorPatientsPatientIdRouteImport } from './routes/doctor.patients.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsIndexRoute = DoctorPatientsIndexRouteImport.update({
  id: '/doctor/patients/',
  path: '/doctor/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsPatientIdRoute = DoctorPatientsPatientIdRouteImport.update({
  id: '/doctor/patients/$patientId',
  path: '/doctor/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients': typeof DoctorPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor/dashboard'
    | '/doctor/patients/$patientId'
    | '/doctor/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor/dashboard'
    | '/doctor/patients/$patientId'
    | '/doctor/patients'
  id:
    | '__root__'
    | '/'
    | '/doctor/dashboard'
    | '/doctor/patients/$patientId'
    | '/doctor/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorPatientsPatientIdRoute: typeof DoctorPatientsPatientIdRoute
  DoctorPatientsIndexRoute: typeof DoctorPatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/': {
      id: '/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof DoctorPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/$patientId': {
      id: '/doctor/patients/$patientId'
      path: '/doctor/patients/$patientId'
      fullPath: '/doctor/patients/$patientId'
      preLoaderRoute: typeof DoctorPatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorPatientsPatientIdRoute: DoctorPatientsPatientIdRoute,
  DoctorPatientsIndexRoute: DoctorPatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
